

name: annotator-env

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - gcc_linux-64=11.4      
  - gxx_linux-64=11.4      
  - scipy=1.11.4       
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.0
  - matplotlib-base
  - pillow
  - rapidfuzz
  - tqdm
  - jupyter
  - scanpy=1.10.1
  - transformers
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8  

  - pip
  - pip:
    - torchsort==0.1.9
    - torch-geometric  
    - torchcp==1.0.2
    - celltypist==1.6.3
