

name: annotator-env

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:

  - python=3.11
  - gcc_linux-64      
  - gxx_linux-64      

  - scipy=1.11.4       
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.0
  - matplotlib-base
  - pillow
  - rapidfuzz
  - tornado
  - tqdm
  - scanpy=1.10.1
  - transformers
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=11.8  

  # pip-only extras 
  - pip
  - pip:
    - torch-geometric  
    - torchcp==1.0.2
    - celltypist==1.6.3
    - git+https://github.com/teddykoker/torchsort.git
